### ISSUE TITLE
GGUF usage

### ISSUE THREAD

**Issue by silvacarl2** [edwko/OuteTTS#15]
with GGUF, we are getting this error:

Using fallback chat format: llama-2
Exception ignored in: <function Llama.__del__ at 0x7f68ee54b7f0>
Traceback (most recent call last):
  File "/home/silvacarl/.local/lib/python3.10/site-packages/llama_cpp/llama.py", line 2201, in __del__
  File "/home/silvacarl/.local/lib/python3.10/site-packages/llama_cpp/llama.py", line 2198, in close
  File "/usr/lib/python3.10/contextlib.py", line 584, in close
  File "/usr/lib/python3.10/contextlib.py", line 576, in __exit__
  File "/usr/lib/python3.10/contextlib.py", line 561, in __exit__
  File "/usr/lib/python3.10/contextlib.py", line 340, in __exit__
  File "/home/silvacarl/.local/lib/python3.10/site-packages/llama_cpp/_internals.py", line 69, in close
  File "/usr/lib/python3.10/contextlib.py", line 584, in close
  File "/usr/lib/python3.10/contextlib.py", line 576, in __exit__
  File "/usr/lib/python3.10/contextlib.py", line 561, in __exit__
  File "/usr/lib/python3.10/contextlib.py", line 449, in _exit_wrapper
  File "/home/silvacarl/.local/lib/python3.10/site-packages/llama_cpp/_internals.py", line 63, in free_model
TypeError: 'NoneType' object is not callable

**Comment by edwko** [comment]
This issue seems to be related to `llama-cpp-python`. You might find more details here: [GitHub Issue #806](https://github.com/abetlen/llama-cpp-python/issues/806). Additionally, you could try this suggested solution: [Issue #1610 - Comment](https://github.com/abetlen/llama-cpp-python/issues/1610#issuecomment-2426080234).

**Comment by silvacarl2** [comment]
thx checking that out

**Comment by tushar-31093** [comment]
For GGUF, can you suggest how to speed up inference? Using quantized models as well to test but doesnt work as such. Also, if it were compatible to LMStudio or Ollama, then inference could be made easier than installing loads of libraries etc.
