### ISSUE TITLE
NameError: name 'exllamav2_ext' is not defined

### ISSUE THREAD

**Issue by todsj88** [edwko/OuteTTS#50]
The following error occurred and I haven't used any exllama in script. Only tried HF and llama-cpp.

Traceback (most recent call last):
  File "C:\tts2.py", line 1, in <module>
    import outetts
  File "D:\anaconda3\Lib\site-packages\outetts\__init__.py", line 3, in <module>
    from .interface import InterfaceHF, InterfaceGGUF, InterfaceEXL2, display_available_models
  File "D:\anaconda3\Lib\site-packages\outetts\interface.py", line 2, in <module>
    from .version.v1.interface import InterfaceHF as _InterfaceHF_v1
  File "D:\anaconda3\Lib\site-packages\outetts\version\v1\interface.py", line 3, in <module>
    from .model import HFModel, GGUFModel, EXL2Model, GenerationConfig
  File "D:\anaconda3\Lib\site-packages\outetts\version\v1\model.py", line 13, in <module>
    from exllamav2 import ExLlamaV2, ExLlamaV2Config, ExLlamaV2Cache, ExLlamaV2Tokenizer
  File "D:\anaconda3\Lib\site-packages\exllamav2\exllamav2\__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "D:\anaconda3\Lib\site-packages\exllamav2\exllamav2\model.py", line 35, in <module>
    from exllamav2.config import ExLlamaV2Config
  File "D:\anaconda3\Lib\site-packages\exllamav2\exllamav2\config.py", line 5, in <module>
    from exllamav2.stloader import STFile, cleanup_stfiles
  File "D:\anaconda3\Lib\site-packages\exllamav2\exllamav2\stloader.py", line 5, in <module>
    from exllamav2.ext import none_tensor, exllamav2_ext as ext_c
  File "D:\anaconda3\Lib\site-packages\exllamav2\exllamav2\ext.py", line 291, in <module>
    ext_c = exllamav2_ext
            ^^^^^^^^^^^^^

**Comment by edwko** [comment]
Seems like an issue with your exllamav2 installation. Try uninstalling it if you won't use it. You could also try upgrading or reinstalling it, here's a related issue: https://github.com/turboderp/exllamav2/issues/159

Also try running this in a separate file to see what you get:
```python
from exllamav2 import ExLlamaV2, ExLlamaV2Config, ExLlamaV2Cache, ExLlamaV2Tokenizer
```

**Comment by todsj88** [comment]
Thanks for your comment.
I have tried:

1. insert your code into my script -> failed
2. insert your code into ext.py -> failed (I was curious) 
3. uninstall exllamav2 -> uninstall failed
4. try below codes  -> failed
   > git clone https://github.com/turboderp/exllamav2.git
   > python setup.py build_ext --inplace

My current setup is as follows:    
Name: torch
Version: 2.5.1+cu124
Name: torchaudio
Version: 2.5.1
Name: torchvision
Version: 0.20.1+cu124
 
If my setup cannot meet requirement, I think I can't go further.

**Comment by edwko** [comment]
You should be fine. Maybe there's some kind of conflict if you installed everything in one environment, as outetts package doesn't install exllamav2 by default, you must have had it before.

I'd suggest starting with a fresh environment. You can do something like:
```bash
python -m venv /path/to/environment
source /path/to/environment/bin/activate
```

From your log messages it looks like you're using Windows and CUDA 12.4, so you can run:
```bash
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
```
(If not, choose appropriate version from PyTorch)

Then install:
```bash
pip install outetts
```

Run with this environment, it should work.

**Comment by todsj88** [comment]
Thanks for your comment again.
You are right. I have only 1 environment.
Also I have not used exllamav2 in my script so I still dont understand why I encountered errors of exllamav2.

I got some information from other repositories. There could be a version conflict like you said. However I cannot change versions because iit caused other script's conflict unless I create new environment.

I think I better use previous outetts now. It still work fine for me.

Thanks!
